const JOBS_DATA = [
    // --- OFF-CAMPUS / FRESHER DRIVES ---
    {
      id: 1,
      title: "Graduate Engineer Trainee",
      company: "Infosys",
      location: "Bangalore",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "Python", "SQL", "Communication"],
      source: "Naukri",
      postedDaysAgo: 1,
      salaryRange: "3.5–5 LPA",
      applyUrl: "https://www.infosys.com/careers",
      description: "Join Infosys as a Graduate Engineer Trainee. You will undergo intensive training in the latest technologies. Ideal for fresh graduates with a passion for coding and problem-solving. Good communication skills are mandatory."
    },
    {
      id: 2,
      title: "Systems Engineer",
      company: "TCS",
      location: "Pune",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["C++", "Java", "Data Structures", "Problem Solving"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "3.3–7 LPA",
      applyUrl: "https://www.tcs.com/careers",
      description: "TCS is hiring Systems Engineers for the Digital and Innovator profiles. Strong grasp of DSA and one programming language required. You will work on enterprise-scale applications for global clients."
    },
    {
      id: 3,
      title: "Associate Software Engineer",
      company: "Accenture",
      location: "Gurgaon",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Cloud Basics", "Java", ".NET", "Agile"],
      source: "Naukri",
      postedDaysAgo: 0,
      salaryRange: "4.5–6 LPA",
      applyUrl: "https://www.accenture.com/in-en/careers",
      description: "Be a part of Accenture's Advanced Technology Centers in India. We are looking for Associate Software Engineers to build and deliver high-quality technology solutions. Training provided on specific tech stacks."
    },
    {
      id: 4,
      title: "Project Engineer",
      company: "Wipro",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Project Management", "Java", "Testing"],
      source: "Indeed",
      postedDaysAgo: 3,
      salaryRange: "3.5 LPA",
      applyUrl: "https://careers.wipro.com/",
      description: "Wipro is hiring Project Engineers for its Turbo hiring program. Candidates should have a B.Tech/B.E degree. Responsibilities include coding, testing, and debugging software applications."
    },
    {
      id: 5,
      title: "Programmer Analyst",
      company: "Cognizant",
      location: "Chennai",
      mode: "Onsite",
      experience: "0-1",
      skills: ["SQL", "Java", "Web Technologies"],
      source: "LinkedIn",
      postedDaysAgo: 5,
      salaryRange: "4–5.5 LPA",
      applyUrl: "https://careers.cognizant.com/global/en",
      description: "Cognizant is looking for Programmer Analysts (GenC). You will be responsible for developing and maintaining software solutions. Knowledge of RDBMS and OOPs concepts is essential."
    },
    {
      id: 6,
      title: "Analyst",
      company: "Capgemini",
      location: "Mumbai",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["C", "C++", "Java", "Good Attitude"],
      source: "Naukri",
      postedDaysAgo: 4,
      salaryRange: "4–7.5 LPA",
      applyUrl: "https://www.capgemini.com/careers/",
      description: "Capgemini is hiring for the Analyst role. We value adaptability and separate capability in learning new technologies. Open to all engineering branches."
    },
    {
      id: 7,
      title: "Software Engineer",
      company: "HCLTech",
      location: "Noida",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Python", "Scripting", "Linux"],
      source: "Indeed",
      postedDaysAgo: 6,
      salaryRange: "3.5–4.5 LPA",
      applyUrl: "https://www.hcltech.com/careers",
      description: "Entry-level Software Engineer position at HCLTech. You will be working on infrastructure and application services. Basic knowledge of Linux and scripting is preferred."
    },
    {
      id: 8,
      title: "Associate System Engineer",
      company: "IBM",
      location: "Bangalore",
      mode: "Remote",
      experience: "0-1",
      skills: ["Cloud", "AI Basics", "Python", "Problem Solving"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "4.5–6 LPA",
      applyUrl: "https://www.ibm.com/in-en/employment/",
      description: "Join IBM as an Associate System Engineer. Work on cutting-edge technologies like Cloud and AI. Good analytical and problem-solving skills are required."
    },
    {
      id: 9,
      title: "Technical Support Engineer",
      company: "Dell Technologies",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "0-2",
      skills: ["Networking", "Hardware", "Communication", "Troubleshooting"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "5–8 LPA",
      applyUrl: "https://jobs.dell.com/",
      description: "Dell is hiring Technical Support Engineers. You will provide enterprise-level support to global customers. Strong knowledge of networking and computer hardware is essential."
    },
    {
      id: 10,
      title: "Software Developer",
      company: "Oracle",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Java", "SQL", "Database", "Cloud"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "10–18 LPA",
      applyUrl: "https://www.oracle.com/corporate/careers/",
      description: "Oracle is hiring fresh graduates for the Server Technology group. Deep understanding of Database internals, SQL, and Java is required. This is a high-impact R&D role."
    },
  
    // --- INTERNSHIPS ---
    {
      id: 11,
      title: "SDE Intern",
      company: "Amazon",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["DSA", "Java", "C++", "Problem Solving"],
      source: "Amazon Jobs",
      postedDaysAgo: 1,
      salaryRange: "₹80k/month Internship",
      applyUrl: "https://www.amazon.jobs/en",
      description: "6-month SDE Internship at Amazon. You will work on real-world scalability problems. Strong command over Data Structures and Algorithms is mandatory. PPO opportunities available."
    },
    {
      id: 12,
      title: "Frontend Intern",
      company: "Swiggy",
      location: "Bangalore",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["React", "JavaScript", "CSS", "Redux"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "₹30k–₹50k/month Internship",
      applyUrl: "https://careers.swiggy.com/",
      description: "Swiggy is looking for Frontend Interns to work on their consumer-facing app. Proficiency in React and modern JavaScript is required. Experience with consumer apps is a plus."
    },
    {
      id: 13,
      title: "Data Analyst Intern",
      company: "PhonePe",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["SQL", "Excel", "Python", "Data Visualization"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "₹40k/month Internship",
      applyUrl: "https://www.phonepe.com/careers/",
      description: "Join the Data team at PhonePe. You will help analyze user transaction behaviors. Strong SQL skills and familiarity with Python (Pandas) are expected."
    },
    {
      id: 14,
      title: "Product Design Intern",
      company: "CRED",
      location: "Bangalore",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Figma", "UI/UX", "Visual Design", "Prototyping"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "₹50k/month Internship",
      applyUrl: "https://careers.cred.club/",
      description: "CRED is hiring Product Design Interns with a high bar for visual aesthetics. You will work closely with senior designers on the core app experience. Portfolio is mandatory."
    },
    {
      id: 15,
      title: "Backend Intern",
      company: "Razorpay",
      location: "Bangalore",
      mode: "Remote",
      experience: "Fresher",
      skills: ["Go", "PHP", "API Design", "Database"],
      source: "Instahyre",
      postedDaysAgo: 4,
      salaryRange: "₹35k/month Internship",
      applyUrl: "https://razorpay.com/jobs/",
      description: "Razorpay Engineering is looking for backend interns. Exposure to Go or PHP is preferred. You will work on payment gateway integrations and settlements."
    },
    {
      id: 16,
      title: "QA Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Manual Testing", "Automation Basics", "Java", "Selenium"],
      source: "Zoho Careers",
      postedDaysAgo: 5,
      salaryRange: "₹15k–₹20k/month Internship",
      applyUrl: "https://www.zoho.com/careers/",
      description: "Zoho is hiring QA Interns. You should have a knack for breaking code and finding bugs. Good programming basics are required for automation tasks."
    },
    {
      id: 17,
      title: "Machine Learning Intern",
      company: "Flipkart",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Python", "PyTorch", "NLP", "Machine Learning"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "₹60k/month Internship",
      applyUrl: "https://www.flipkartcareers.com/",
      description: "Flipkart Data Science team is hiring interns. Work on recommendation engines and computer vision models. Strong mathematical background required."
    },
    {
      id: 18,
      title: "Software Engineering Intern",
      company: "Juspay",
      location: "Bangalore",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Haskell", "Functional Programming", "PureScript", "Rust"],
      source: "HackerEarth",
      postedDaysAgo: 6,
      salaryRange: "₹40k/month Internship",
      applyUrl: "https://juspay.in/careers",
      description: "Juspay is solving payments at scale using Functional Programming. We are looking for interns who love FP (Haskell/Rust). Intense learning environment."
    },
    {
      id: 19,
      title: "DevOps Intern",
      company: "Freshworks",
      location: "Chennai",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["AWS", "Linux", "Docker", "Scripting"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "₹25k/month Internship",
      applyUrl: "https://www.freshworks.com/company/careers/",
      description: "Freshworks is hiring DevOps interns. You will learn about CI/CD pipelines, cloud infrastructure, and monitoring tools. Basic Linux knowledge is a must."
    },
    {
      id: 20,
      title: "Android Dev Intern",
      company: "Paytm",
      location: "Noida",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Kotlin", "Android Studio", "Java", "Mobile Dev"],
      source: "LinkedIn",
      postedDaysAgo: 4,
      salaryRange: "₹20k–₹30k/month Internship",
      applyUrl: "https://paytm.com/careers/",
      description: "Paytm is looking for Android Interns. Work on one of India's largest payment apps. Knowledge of Kotlin and Android architecture components is expected."
    },
  
    // --- JUNIOR / EXPERIENCED ROLES ---
    {
      id: 21,
      title: "Java Developer",
      company: "TCS",
      location: "Kolkata",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Java 8", "Spring Boot", "Microservices", "Hibernate"],
      source: "Naukri",
      postedDaysAgo: 0,
      salaryRange: "5–9 LPA",
      applyUrl: "https://www.tcs.com/careers",
      description: "We are looking for Java Developers with 1-3 years of experience. Strong hands-on experience in Spring Boot and Microservices is required. Join our BFSI vertical."
    },
    {
      id: 22,
      title: "React Developer",
      company: "Zomato",
      location: "Gurgaon",
      mode: "Onsite",
      experience: "1-3",
      skills: ["React", "Redux", "JavaScript", "HTML5"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "12–18 LPA",
      applyUrl: "https://www.zomato.com/careers",
      description: "Zomato is hiring React Developers. You will build pixel-perfect, buttery smooth UIs. Experience with high-traffic consumer websites is preferred."
    },
    {
      id: 23,
      title: "Python Developer",
      company: "Infosys",
      location: "Pune",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Python", "Django", "Flask", "API"],
      source: "Indeed",
      postedDaysAgo: 5,
      salaryRange: "5–8 LPA",
      applyUrl: "https://www.infosys.com/careers",
      description: "Infosys is hiring Python Developers. You should have experience with Django or Flask frameworks. Work on automating business processes for global clients."
    },
    {
      id: 24,
      title: "Data Analyst",
      company: "Myntra",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["SQL", "Tableau", "Python", "Analytics"],
      source: "Naukri",
      postedDaysAgo: 1,
      salaryRange: "10–15 LPA",
      applyUrl: "https://careers.myntra.com/",
      description: "Myntra is looking for Data Analysts to join the Growth team. You will query massive datasets to find insights that drive fashion trends and sales."
    },
    {
      id: 25,
      title: "QA Automation Engineer",
      company: "Mindtree",
      location: "Bangalore",
      mode: "Remote",
      experience: "1-3",
      skills: ["Selenium", "Java", "TestNG", "Jenkins"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "6–10 LPA",
      applyUrl: "https://www.mindtree.com/careers",
      description: "Mindtree (LTIMindtree) is hiring Automation Engineers. Proven experience in Selenium WebDriver and Java is required. Experience with CI/CD tools is a plus."
    },
    {
      id: 26,
      title: "Full Stack Developer",
      company: "Startup: AtomicWork",
      location: "Bangalore",
      mode: "Onsite",
      experience: "1-3",
      skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
      source: "Wellfound",
      postedDaysAgo: 0,
      salaryRange: "15–25 LPA",
      applyUrl: "https://atomicwork.com/careers",
      description: "Early-stage startup AtomicWork is looking for a Full Stack Engineer. You will own features end-to-end. High equity component available. Fast-paced environment."
    },
    {
      id: 27,
      title: "Cloud Support Associate",
      company: "Amazon Web Services",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Networking", "Linux", "Windows", "AWS Basics"],
      source: "Amazon Jobs",
      postedDaysAgo: 6,
      salaryRange: "10–14 LPA",
      applyUrl: "https://www.amazon.jobs/en",
      description: "Join AWS as a Cloud Support Associate. You will help global customers troubleshoot their cloud infrastructure. Excellent learning ground for cloud technologies."
    },
    {
      id: 28,
      title: "Business Analyst",
      company: "Deloitte",
      location: "Mumbai",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Analysis", "Requirements Gathering", "Agile", "Excel"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "8–12 LPA",
      applyUrl: "https://www2.deloitte.com/ui/en/careers.html",
      description: "Deloitte India is hiring Business Analysts. You will bridge the gap between business needs and technical solutions. Strong communication skills are paramount."
    },
    {
      id: 29,
      title: "UI Developer",
      company: "Publicis Sapient",
      location: "Gurgaon",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["HTML5", "CSS3", "JavaScript", "React"],
      source: "Indeed",
      postedDaysAgo: 4,
      salaryRange: "10–16 LPA",
      applyUrl: "https://www.publicissapient.com/careers",
      description: "Publicis Sapient is looking for UI Developers. Deep understanding of semantic HTML, CSS, and accessibility standards is required. React experience is preferred."
    },
    {
      id: 30,
      title: "iOS Developer",
      company: "Swiggy",
      location: "Remote",
      mode: "Remote",
      experience: "1-3",
      skills: ["Swift", "iOS SDK", "Xcode", "mobile"],
      source: "LinkedIn",
      postedDaysAgo: 5,
      salaryRange: "18–24 LPA",
      applyUrl: "https://careers.swiggy.com/",
      description: "Swiggy is hiring iOS Engineers. Work on the delivery partner app used by thousands daily. Strong grasp of Swift and concurrency is needed."
    },
    
    // --- MIX OF ROLES TO FILL 60 ---
    {
      id: 31,
      title: "Performance Engineer",
      company: "Salesforce",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "3-5",
      skills: ["Java", "JMeter", "Profiling", "Scalability"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "20–30 LPA",
      applyUrl: "https://www.salesforce.com/company/careers/",
      description: "Salesforce is hiring Performance Engineers. You will ensure our multi-tenant architecture scales. Deep knowledge of JVM internals is required."
    },
    {
      id: 32,
      title: "Product Manager",
      company: "Udaan",
      location: "Bangalore",
      mode: "Onsite",
      experience: "3-5",
      skills: ["Product Management", "Analytics", "Strategy", "B2B"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "25–40 LPA",
      applyUrl: "https://udaan.com/careers",
      description: "Udaan is looking for Product Managers for the supply chain vertical. You will define the roadmap and work with engineering to deliver. B2B experience preferred."
    },
    {
      id: 33,
      title: "SAP ABAP Consultant",
      company: "Tech Mahindra",
      location: "Pune",
      mode: "Hybrid",
      experience: "3-5",
      skills: ["ABAP", "SAP HANA", "OData", "Fiori"],
      source: "Naukri",
      postedDaysAgo: 3,
      salaryRange: "8–14 LPA",
      applyUrl: "https://careers.techmahindra.com/",
      description: "Tech Mahindra is hiring SAP ABAP Consultants. Experience in SAP HANA and OData services is crucial. Should be able to handle client communications."
    },
    {
      id: 34,
      title: "Security Analyst",
      company: "Palo Alto Networks",
      location: "Bangalore",
      mode: "Remote",
      experience: "1-3",
      skills: ["Cybersecurity", "Network Security", "Python", "SOC"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "12–18 LPA",
      applyUrl: "https://www.paloaltonetworks.com/company/careers",
      description: "Join Palo Alto Networks as a Security Analyst. Monitor and respond to security incidents. Knowledge of firewalls and threat landscape is essential."
    },
    {
      id: 35,
      title: "Ruby on Rails Developer",
      company: "Gojek",
      location: "Bangalore",
      mode: "Remote",
      experience: "3-5",
      skills: ["Ruby", "Rails", "Postgres", "Redis"],
      source: "Instahyre",
      postedDaysAgo: 4,
      salaryRange: "30–45 LPA",
      applyUrl: "https://www.gojek.io/careers",
      description: "Gojek is hiring Senior Rails Engineers. You will build the backbone of our superapp. Experience with high-throughput systems is mandatory."
    },
    {
      id: 36,
      title: "Golang Developer",
      company: "BrowserStack",
      location: "Mumbai",
      mode: "Onsite",
      experience: "1-3",
      skills: ["Go", "Distributed Systems", "Linux", "Docker"],
      source: "LinkedIn",
      postedDaysAgo: 5,
      salaryRange: "15–25 LPA",
      applyUrl: "https://www.browserstack.com/careers",
      description: "BrowserStack is looking for Golang developers. We build infrastructure to test on 3000+ devices. Low-level systems knowledge is a big plus."
    },
    {
      id: 37,
      title: "Frontend Developer",
      company: "ShareChat",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React Native", "JavaScript", "Mobile", "Performance"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "15–22 LPA",
      applyUrl: "https://sharechat.com/careers",
      description: "ShareChat is hiring Frontend/Mobile engineers. Work on a vernacular social network with millions of users. React Native experience is highly valued."
    },
    {
      id: 38,
      title: "Data Engineer",
      company: "Walmart Global Tech",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "3-5",
      skills: ["Big Data", "Spark", "Hadoop", "Scala"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "18–28 LPA",
      applyUrl: "https://careers.walmart.com/",
      description: "Walmart is hiring Data Engineers. You will build data pipelines that handle petabytes of retail data. Experience with Spark and Cloud (Azure/GCP) is required."
    },
    {
      id: 39,
      title: "Technical Writer",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "0-2",
      skills: ["Writing", "Documentation", "English", "Coching"],
      source: "Zoho Careers",
      postedDaysAgo: 6,
      salaryRange: "4–6 LPA",
      applyUrl: "https://www.zoho.com/careers/",
      description: "Zoho is hiring Technical Writers. You will write API documentation and help guides for our suite of products. Excellent command over English is required."
    },
    {
      id: 40,
      title: "Network Engineer",
      company: "Cisco",
      location: "Bangalore",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["CCNA", "Networking", "Routing", "Switching"],
      source: "Naukri",
      postedDaysAgo: 3,
      salaryRange: "8–12 LPA",
      applyUrl: "https://jobs.cisco.com/",
      description: "Cisco is looking for Network Engineers. You will work on the next generation of networking hardware and software. CCNA/CCNP certification is a plus."
    },
    {
        id: 41,
        title: "SDE-1",
        company: "Meesho",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "MySQL", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "18-25 LPA",
        applyUrl: "https://meesho.com/careers",
        description: "Join Meesho to build for Bharat. We are looking for SDE-1s to work on our supply chain and reseller platforms. High ownership and fast shipping culture."
    },
    {
        id: 42,
        title: "Frontend Engineer",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Vue.js", "JavaScript", "Go", "Flutter"],
        source: "Zerodha Careers",
        postedDaysAgo: 2,
        salaryRange: "15-20 LPA",
        applyUrl: "https://zerodha.com/careers",
        description: "Zerodha is hiring Frontend Engineers. We use Vue.js heavily. You will work on Kite, Console, and other investment platforms. We value clean code and no-nonsense engineering."
    },
    {
        id: 43,
        title: "Intern (Engineering)",
        company: "Groww",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Spring", "React", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k/month Internship",
        applyUrl: "https://groww.in/careers",
        description: "Groww is looking for Engineering Interns. Work on simplifying investing for millions of Indians. Strong problem-solving skills and CS fundamentals required."
    },
    {
        id: 44,
        title: "Big Data Developer",
        company: "JPMorgan Chase",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Hadoop", "Spark", "Python", "AWS"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "20-30 LPA",
        applyUrl: "https://careers.jpmorgan.com/",
        description: "JPMC is hiring for its CIB Technology team. You will work on large-scale data platforms. Experience with AWS EMR and Spark is mandatory."
    },
    {
        id: 45,
        title: "Software Engineer",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C#", ".NET", "Azure", "Algorithms"],
        source: "Careers Page",
        postedDaysAgo: 2,
        salaryRange: "15-22 LPA",
        applyUrl: "https://careers.microsoft.com/",
        description: "Microsoft IDC is hiring Software Engineers. Work on Azure, Office, or Windows. We look for strong coding skills and ability to design complex systems."
    },
    {
        id: 46,
        title: "Site Reliability Engineer",
        company: "LinkedIn",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Linux", "Automation", "Networking"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "20-30 LPA",
        applyUrl: "https://www.linkedin.com/company/linkedin/jobs/",
        description: "LinkedIn is hiring SREs. You will keep the professional network up and running. Deep Linux internals and automation (Python/Go) knowledge required."
    },
    {
        id: 47,
        title: "Embedded Engineer",
        company: "Qualcomm",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C", "RTOS", "Embedded Systems", "Debugging"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "12-18 LPA",
        applyUrl: "https://qualcomm.com/careers",
        description: "Qualcomm is hiring Embedded Software Engineers for 5G and Modem teams. Strong C programming and OS concepts needed."
    },
    {
        id: 48,
        title: "Graphic Designer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "0-2",
        skills: ["Photoshop", "Illustrator", "Social Media", "Creativity"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "5-8 LPA",
        applyUrl: "https://zomato.com/careers",
        description: "Zomato Marketing team is looking for Graphic Designers. You will create witty and engaging social media creatives. Portfolio is a must."
    },
    {
        id: 49,
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts"],
        source: "Web3.career",
        postedDaysAgo: 2,
        salaryRange: "20-40 LPA",
        applyUrl: "https://polygon.technology/careers",
        description: "Polygon is hiring Protocol Engineers. Work on scaling Ethereum. Deep understanding of EVM and consensus algorithms is required."
    },
    {
        id: 50,
        title: "Flutter Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Flutter", "Dart", "Mobile", "State Management"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "15-25 LPA",
        applyUrl: "https://www.dream11.com/careers",
        description: "Dream11 is hiring Flutter Developers. Build sports fantasy apps for millions of users. Experience with complex state management is needed."
    },
    {
        id: 51,
        title: "Cyber Security Intern",
        company: "Wipro",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Network Security", "Ethical Hacking", "Linux", "Tools"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://careers.wipro.com/",
        description: "Wipro Cyber Security practice is hiring interns. Learn about VAPT, SOC monitoring, and identity management. Certification in CEH is a plus."
    },
    {
        id: 52,
        title: "Game Developer",
        company: "MPL (Mobile Premier League)",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Unity", "C#", "Game Design", "Multiplayer"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "14-22 LPA",
        applyUrl: "https://www.mpl.live/careers",
        description: "MPL is hiring Game Developers. You will build casual mobile games using Unity. Experience with multiplayer game networking is essential."
    },
    {
        id: 53,
        title: "Product Analyst",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SQL", "Looker", "Product Analytics", "Python"],
        source: "Instahyre",
        postedDaysAgo: 3,
        salaryRange: "12-16 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Razorpay is hiring Product Analysts. You will work with PMs to drive product adoption and metrics. Strong SQL and storytelling skills needed."
    },
    {
        id: 54,
        title: "DevRel Engineer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["APIs", "Communication", "Content Creation", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "15-25 LPA",
        applyUrl: "https://www.postman.com/careers/",
        description: "Postman is hiring Developer Relations Engineers. You will advocate for Postman in the community, write blogs, and speak at conferences."
    },
    {
        id: 55,
        title: "AI Research Intern",
        company: "Google Research India",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["TensorFlow", "Research", "Math", "Python"],
        source: "Google Careers",
        postedDaysAgo: 5,
        salaryRange: "₹1L/month Internship",
        applyUrl: "https://research.google/careers/",
        description: "Google Research India is hiring interns for its AI/ML labs. Work on publishing papers in top conferences. PhD or Masters students preferred."
    },
    {
        id: 56,
        title: "Salesforce Developer",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-2",
        skills: ["Apex", "Visualforce", "Salesforce", "Java"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "6-9 LPA",
        applyUrl: "https://www2.deloitte.com/ui/en/careers.html",
        description: "Deloitte is looking for Salesforce Developers. You will build custom applications on the Salesforce platform. Certification is highly valued."
    },
    {
        id: 57,
        title: "React Native Developer",
        company: "NoBroker",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React Native", "Redux", "Mobile", "Android/iOS"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10-16 LPA",
        applyUrl: "https://nobroker.in/careers",
        description: "NoBroker is hiring React Native developers. Help us eliminate brokerage from real estate. Experience in publishing apps to Play Store/App Store is needed."
    },
    {
        id: 58,
        title: "Support Engineer",
        company: "Zoho",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Communication", "Troubleshooting", "Tech Support", "Basic Coding"],
        source: "Zoho Careers",
        postedDaysAgo: 4,
        salaryRange: "3-5 LPA",
        applyUrl: "https://www.zoho.com/careers/",
        description: "Zoho is hiring Support Engineers. You will assist customers with technical queries via chat/email. Good written communication is mandatory."
    },
    {
        id: 59,
        title: "Marketing Intern",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Marketing", "Social Media", "Content", "Communication"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹15k/month Internship",
        applyUrl: "https://unacademy.com/careers",
        description: "Unacademy is looks for Marketing Interns. You will help execute campaigns and manage campus ambassadors. High energy and creativity required."
    },
    {
        id: 60,
        title: "Implementation Engineer",
        company: "Chargebee",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["API", "Integration", "SaaS", "Customer Success"],
        source: "Instahyre",
        postedDaysAgo: 2,
        salaryRange: "8-14 LPA",
        applyUrl: "https://www.chargebee.com/careers",
        description: "Chargebee is hiring Implementation Engineers. You will help customers integrate our billing logic into their stack. API knowledge is critical."
    }
  ];
